apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstores.kubernetes
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: kubernetesMountPath # Default path where secrets are mounted
    value: "/mnt/secrets"
  - name: namespace # Namespace where secrets are stored. If empty, uses component's namespace.
    value: "default" # Adjust if secrets are in a different namespace
